backend:
  name: github
  repo: DomtronVox/StaticTemplateSite # Path to your Github repository
  branch: master # Branch to update

media_folder: src/files/images/
public_folder: images/

collections: # A list of collections the CMS should be able to edit
  - label: "Site Settings"
    name: "site_config"
    files:
      - label: "General Settings"
        name: "general_config"
        file: "src/documents/config/site.json"
        fields:
          - {label: "'Brand' (e.g. Company Inc.)", name: "brand", widget: "string"}
          - {label: "Title (added to page header as large text)", name: "title", widget: "string"}
          - {label: "Subtitle (added to page headers as small text)", name: "subtitle", widget: "string"}
          - {label: "Site Description (used for search engine bots)", name: "description", widget: "string"}
          - {label: "URL (e.g. http://your-site.com/)", name: "url", widget: "string"}    
          - {label: "Favicon (the icon that appears in the browser tabs)", name: "favicon_image", widget: "image"}
          - {label: "Logo (the image used as the logo)", name: "logo_image", widget: "image"}
          - {label: "Name of Site Posts (Examples: 'Blog' or 'News')", name: "posts_name", widget: "string"}
          - {label: "Name of Extra Links sidebar (Examples: 'Our Friends' or 'Interesting Links')", name: "sidebar_links_name", widget: "string"}
          - label: "Sidebar Extra Links (leave empty to remove the extra sidebar)"
            name: "sidebar_links_list"
            widget: "list"
            fields:
                  - {label: "Link Text", name: "text", widget: "string"} 
                  - {label: "Link URL (i.e. relative like /about.html or absolute like http://coolsite.org/cool_things.html)", name: "link", widget: "string"} 
      - label: "Layout Settings"
        name: "layout_config"
        file: "src/documents/config/positioning.json"
        fields:
          - {label: "Menu Bar Location", name: "nav_position", widget: "select", default: "top", options: ["top", "in_header", "left", "right"] }
          - {label: "Sidebar Location", name: "aside_position", widget: "select", default: "right", options: ["right", "left", "off"] }
      - label: "Main Menu"
        name: "menu_config"
        file: "src/documents/config/menu.json"
        fields:
          - label: "Menu Pages and Order"
            name: "menu_config_list"
            widget: "list"
            fields:
              - {label: "Menu Text", name: "text", widget: "string"} 
              - {label: "Menu Link (i.e. relative like /about.html or absolute like http://coolsite.org/cool_things.html)", name: "link", widget: "string"} 
              - label: "Sub-Menu Pages and Order"
                name: "sub-menu_config_list"
                widget: "list"
                fields:
                  - {label: "Sub-Menu Text", name: "text", widget: "string"} 
                  - {label: "Sub-Menu Link (i.e. relative like /about.html or absolute like http://coolsite.org/cool_things.html)", name: "link", widget: "string"}
              
  - name: "pages"
    label: "Pages"
    folder: "src/documents"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Collection", name: "collection", widget: "hidden", default: "Pages"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default.pug"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"} 
      
  - name: "posts"
    label: "Blog/News Posts"
    folder: "src/documents/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Collection", name: "collection", widget: "hidden", default: "posts"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default.pug"}
      - {label: "Publish Date (note no a scheduler, is just the date people see)", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"} 

